development:
  adapter: postgresql
  database: myapp
production:
  adapter: postgresql
  port: 5432
  database: 5432/d8lc02ov6ga41v
  username: ewcrkuwzevdfck
  password: bCrGZUPoyBu-zv-7QLHF7KRYwM
  host: c2-54-204-42-178.compute-1.amazonaws.com

